
# Default values for postgres-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

images:
  operator:
    repository: registry.opensource.zalan.do/acid/postgres-operator
    tag: v1.8.1
    pullPolicy: IfNotPresent
