#---
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: {{ template "stan.name" . }}
#  labels:
#    app: {{ template "stan.name" . }}
#    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
#  {{ if .Values.global.enableArgoCDAnnotation }}
#  annotations:
#    argocd.argoproj.io/sync-wave: "-1"
#  {{- end }}
#automountServiceAccountToken: false