#################################
### Astronomer global configuration
#################################
global:
  # Base domain for all subdomains exposed through ingress
  baseDomain: istio3533new.astrodev.io

  # Name of secret containing TLS certificate
  tlsSecret: astronomer-tls

  istio:
    enabled: false
    rootNamespace: "istio-system"
  istioEnabled: false

  # Enable privateCaCerts only if your enterprise security team
  # generated a certificate from a private certificate authority.
  # Create a generic secret for each cert, and add it to the list below.
  # Each secret must have a data entry for 'cert.pem'
  # Example command: `kubectl create secret generic private-root-ca --from-file=cert.pem=./<your-certificate-filepath>`
#  privateCaCerts: []
  #  privateCaCerts:
  #    - private-root-ca


  # Enable privateCaCertsAddToHost only when your nodes do not already
  # include the private CA in their docker trust store.
  # Most enterprises already have this configured,
  # and in that case 'enabled' should be false.
  #  privateCaCertsAddToHost:
  #    enabled: false
  #    hostDirectory: /etc/docker/certs.d
  #    certCopier:
  #      repository: alpine
  #      tag: 3.14
  #      pullPolicy: IfNotPresent
#  privateCaCertsAddToHost:
  #    enabled: true
  #    hostDirectory: /etc/docker/certs.d

  # For development or proof-of-concept, you can use an in-cluster database
  postgresqlEnabled: false

  networkPolicy:
    enabled: true

  # Enables using SSL connections to
  # encrypt client/server communication
  # between databases and the Astronomer platform.
  # If your database enforces SSL for connections,
  # change this value to true
  ssl:
    enabled: false

#################################
### Nginx configuration
#################################
nginx:
  # IP address the nginx ingress should bind to
  loadBalancerIP: 34.138.236.80
  # Dict of arbitrary annotations to add to the nginx ingress. For full configuration options, see https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/
  ingressAnnotations: { }

#################################
### SMTP configuration
#################################

astronomer:
  houston:
    config:
      publicSignups: true # Users need to be invited to have access to Astronomer. Set to true otherwise
      emailConfirmation: false # Users get an email verification before accessing Astronomer
      deployments:
        logHelmValues: true
        manualReleaseNames: true # Allows you to set your release names
        serviceAccountAnnotationKey: iam.gke.io/gcp-service-account  # Flag to enable using IAM roles (don't enter a specific role)
      email:
        enabled: false
        reply: "noreply@astronomer.io" # Emails will be sent from this address
      auth:
        github:
          enabled: true # Lets users authenticate with Github
        local:
          enabled: true # Disables logging in with just a username and password
        openidConnect:
          google:
            enabled: true # Lets users authenticate with Google
    secret: [ ]
    # secret:
    #   - envName: "smtps://USERNAME:PW@HOST/?pool=true"  # Reference to the Kubernetes secret for SMTP credentials. Can be removed if email is not used.
    #     secretName: "astronomer-smtp"
    #     secretKey: "connection"

stan:
  logging:
    debug: true