#################################
## Postgres Operator Service ####
#################################
apiVersion: v1
kind: Service
metadata:
  name: {{ template "postgres-operator.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    tier: {{ template "postgres-operator.name" . }}
    component: {{ template "prometheus.name" $ }}
    chart: {{ template "prometheus.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: postgres-operator
