apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ .Values.cluserName}}
  namespace: {{ .Release.Namespace }}
  labels:
    tier: {{ template "postgres-operator.name" . }}
    component: {{ template "postgres-operator.name" . }}
    chart: {{ template "postgres-operator.chart" . }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
spec:
  tls:
    secretName: astronomer-tls
    certificateFile: "tls.crt"
    privateKeyFile: "tls.key"
    caSecretName: private-ca
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    zalando:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  databases:
    foo: zalando  # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "14"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "postgres-operator.fullname" . }}-instance-policy
  namespace: {{ .Release.Namespace }}
  labels:
    tier: {{ template "postgres-operator.name" . }}
    component: {{ template "postgres-operator.name" . }}
    chart: {{ template "postgres-operator.chart" . }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  podSelector:
    matchLabels:
      cluster-name: {{ .Values.cluserName }}
  ingress:
    # Allow inbound connections
    - ports:
      - port: 5432
