apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ .Values.clusterName}}
  namespace: {{ .Release.Namespace }}
  labels:
    tier: {{ template "postgres-operator.name" . }}
    component: {{ template "postgres-operator.name" . }}
    chart: {{ template "postgres-operator.chart" . }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "10"
spec:
{{ toYaml  .Values.postgres | indent 2 }}

