#################################
## Postgres Operator Deployment #
#################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-operator
  namespace: {{ .Release.Namespace }}
  labels:
    tier: {{ template "postgres-operator.name" . }}
    component: {{ template "postgres-operator.name" . }}
    chart: {{ template "postgres-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.operator.replicas }}
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
      tier: {{ template "postgres-operator.name" . }}
      component: {{ template "postgres-operator.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        tier: {{ template "postgres-operator.name" . }}
        component: {{ template "postgres-operator.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: postgres-operator
      containers:
      - name: postgres-operator
        # IMPORTANT when we inevitably need to upgrade this we need to make sure we also copy the new crd file ./crds/postgresql.crd.yaml
        image: {{ include "operator.image" . }}
        imagePullPolicy: {{ .Values.images.operator.pullPolicy }}
        resources:
{{ toYaml .Values.operator.resources | indent 10 }}
        securityContext:
{{ toYaml .Values.operator.securityContext | indent 10 }}
        env:
        # provided additional ENV vars can overwrite individual config map entries
        - name: CONFIG_MAP_NAME
          value: "postgres-operator"
        # In order to use the CRD OperatorConfiguration instead, uncomment these lines and comment out the two lines above
        # - name: POSTGRES_OPERATOR_CONFIGURATION_OBJECT
        #  value: postgresql-operator-default-configuration
        # Define an ID to isolate controllers from each other
        # - name: CONTROLLER_ID
        #   value: "second-operator"
