################################
## KubeD (Cluster)RoleBinding
#################################
# Either:
# 1. Do not create anything if rbacEnabled is disabled
# 2. Create RoleBinding for each namespace in the namespacePool + release if namespacePools is enabled
# 3. Otherwhise, create ClusterRoleBinding
{{- $useClusterRoles := not .Values.global.features.namespacePools.enabled }}
{{- $namespaces := .Values.global.features.namespacePools.namespaces.names }}
{{ if $useClusterRoles }}
  {{- $namespaces = list .Release.Namespace}}
{{ else }}
  {{ $namespaces = append $namespaces .Release.Namespace}}
{{ end }}

{{- if .Values.global.rbacEnabled }}
{{- range $i, $namespaceName := $namespaces -}}
---
apiVersion: {{ template "apiVersion.rbac" . }}
kind: {{ if $useClusterRoles }}ClusterRoleBinding{{ else }}RoleBinding{{ end }}
metadata:
  name: {{ template "kubed.fullname" $ }}
  {{- if not $useClusterRoles }}
  namespace: {{ $namespaceName }}
  {{- end }}
  labels:
    tier: {{ template "kubed.name" $ }}
    component: {{ template "kubed.name" $ }}
    chart: {{ template "kubed.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ if $useClusterRoles }}ClusterRole{{ else }}Role{{ end }}
  name: {{ template "kubed.fullname" $ }}
subjects:
- kind: ServiceAccount
  name: {{ template "kubed.serviceAccountName" $ }}
  namespace: {{ $.Release.Namespace }}
{{ end }}
{{ end }}
